# Generated by Django 2.1 on 2019-01-05 18:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_address', models.TextField(max_length=150)),
                ('sender_phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('receiver_name', models.CharField(max_length=100)),
                ('receiver_phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('receiver_postal_code', models.PositiveIntegerField(default=15987, max_length=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('receiver_address', models.CharField(max_length=150)),
                ('receiver_detail_address', models.CharField(max_length=100)),
                ('customs_id', models.CharField(max_length=10)),
                ('item_url', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('width', models.DecimalField(decimal_places=3, max_digits=40)),
                ('length', models.DecimalField(decimal_places=3, max_digits=40)),
                ('height', models.DecimalField(decimal_places=3, max_digits=40)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=40)),
                ('box_qty', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('item_name', models.CharField(max_length=100)),
                ('transit_memo', models.CharField(default='', max_length=100)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('item_qty', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('email', models.CharField(max_length=100)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('website', models.URLField(default='')),
                ('phone', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
