# Generated by Django 2.1 on 2019-01-05 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userInputs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
